### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by Delta09** [raghavgupta96/gratis-landing#10]
There is no google analytics script in the website.

- It was added in commit  [d5854](https://github.com/raghavgupta96/gratis-landing/commit/d58540873d09238c56753b7a9da9da7d3a0d4bb3)
- It existed until commit/PR [f886d](https://github.com/raghavgupta96/gratis-landing/commit/f886dc81e2c3558ace3808da0d7f6769ca8c640b)
- All instances of it do not exist from commit [e8854](https://github.com/raghavgupta96/gratis-landing/commit/e8854ee92ba6ce01193852af498a13f8459ecfac)

**Comment by raghavgupta96** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Landing page work](https://trello.com/c/sVyMDRDm/17-landing-page-work)
