### ISSUE TITLE
GO TO Webapp

### ISSUE THREAD

**Issue by raghavgupta96** [raghavgupta96/gratis-landing#4]
Go to webapp does what is meant to be done but is currently not needed. The webapp is only for restaurants and should not be put on the landing page. 

Can this section be removed entirely and just have a count down to when we are expected to have our beta launch?

**Comment by Delta09** [comment]
Do you want to put a countdown timer?

**Comment by raghavgupta96** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Landing page work](https://trello.com/c/sVyMDRDm/17-landing-page-work)
