### ISSUE TITLE
Need Better Image

### ISSUE THREAD

**Issue by Delta09** [raghavgupta96/gratis-landing#8]
![image](https://user-images.githubusercontent.com/10010080/52516066-7d347c00-2bd9-11e9-8871-b4daae54ecfa.png)

Suggestion to obtain a higher quality logo of the SJSU Newman Center. Perhaps we can ask them for one

**Comment by raghavgupta96** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Landing page work](https://trello.com/c/sVyMDRDm/17-landing-page-work)
